#!/usr/bin/env python3
"""Check catalog coverage, evidence, and regenerate the pricing coverage table."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from pricing_registry import PricingRegistry


def main():
    import yaml
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--release", action="store_true", help="require all non-disabled models to have enabled verified profiles")
    args = parser.parse_args()
    registry = PricingRegistry()
    catalog = yaml.safe_load((ROOT / "litellm_config.yaml").read_text())["model_list"]
    errors, rows = [], []
    counts = {"enabled": 0, "blocked": 0, "disabled": 0}
    aliases = {m["model_name"] for m in catalog}
    if aliases != set(registry.models):
        errors.append("Catalog and pricing alias sets differ")
    for item in catalog:
        alias = item["model_name"]
        model = registry.models.get(alias, {})
        if model.get("deployment_model", model.get("upstream_model")) != item["litellm_params"]["model"]:
            errors.append(f"{alias}: upstream drift")
        profiles = [registry.profiles[v] for v in model.get("profiles", [])]
        enabled = [p for p in profiles if p["enabled"]]
        if args.release and not model.get("disabled") and not enabled:
            errors.append(f"{alias}: no accepted pricing profile")
        for profile in profiles:
            vendor = registry.document["vendors"][profile["vendor"]]
            if not (ROOT / vendor["procedure"]).is_file():
                errors.append(f"{alias}: missing vendor verification procedure")
            for evidence in profile["evidence"] + profile["acceptance_evidence"]:
                if not (ROOT / evidence).is_file():
                    errors.append(f"{alias}: missing evidence {evidence}")
        state = "disabled" if model.get("disabled") else "enabled" if enabled else "blocked"
        counts[state] += 1
        reason = "; ".join(sorted({p.get("block_reason", "") for p in profiles if p.get("block_reason")}))
        rows.append(f"| `{alias}` | `{model.get('upstream_model', '?')}` | {state} | {reason} |")
    summary = (f"**{counts['blocked']} blocked aliases; {counts['enabled']} aliases with accepted profiles; "
               f"{counts['disabled']} intentionally disabled.** Enabled means supported routes/options; catalog rates are accepted by default.\n\n")
    document = "# Pricing coverage\n\nGenerated by `python scripts/pricing_coverage.py --write`.\n\n" + summary + "Native prices come from the captured LiteLLM catalog; custom-provider rates and\nexplicit corrections carry vendor evidence. Run `--release` before promotion.\n\n| Alias | Exact upstream | Admission | Outstanding evidence |\n| --- | --- | --- | --- |\n" + "\n".join(rows) + "\n"
    path = ROOT / "docs/pricing-coverage.md"
    if args.write:
        path.write_text(document)
    elif not path.exists() or path.read_text() != document:
        errors.append("Pricing coverage documentation needs regeneration")
    for error in errors:
        print(error, file=sys.stderr)
    print(f"Checked {len(catalog)} aliases and {len(registry.profiles)} profiles; {len(errors)} errors")
    return bool(errors)


if __name__ == "__main__":
    raise SystemExit(main())
